### ISSUE TITLE
Close the menu?

### ISSUE THREAD

**Issue by alexiovay** [appleple/hiraku#4]
Hey, 

is there any option to close the menu?

**Comment by steelydylan** [comment]
Hi :D
sorry we haven't prepared any option to close the menu
But I'll prepare the option soon ;)
I'll let you know when I'm done :)
thanks

**Comment by alexiovay** [comment]
What  could I do with Javascript then to have a solution for this?

Thank you.

**Comment by steelydylan** [comment]
While opening the offcanvas menu, you can find the main canvas covered with gray filter
If you tap/click the area, you can close the offcanvas menu.
So if you want to close the menu with JavaScript, you may want to write as follows

`$(".js-hiraku-offcanvas").click()`

**Comment by alexiovay** [comment]
Ah, okay, thanks! 👍  :)
