### ISSUE TITLE
Close button in menu

### ISSUE THREAD

**Issue by Kaorinite** [appleple/hiraku#6]
Hello!

Is it possible to add a close button in the menu itself? I'm using the menu from the left side and the contents are fixed, so there's no button seen. I have no idea how to write the code to do that.

Thanks in advance!

**Comment by steelydylan** [comment]
Hi @Kaorinite 
you can close the menu by the following code

```js
$(".js-hiraku-offcanvas").click()
```

but I'm thinking of adding the option soon ;)

**Comment by Kaorinite** [comment]
@steelydylan Yay, it works! Thanks a lot! :)
